services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbname             # 自定义数据库名
      POSTGRES_USER: username         # 自定义用户名
      POSTGRES_PASSWORD: password     # 自定义密码
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
