services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    ports:
      - 8888:80
    environment:
      - DOMAIN=https://passwd.lisir.me              # 这是您希望与您的 Vaultwarden 实例关联的域名。
      - LOGIN_RATELIMIT_MAX_BURST=10                # 允许在一阵登录/两步验证尝试中的最大请求次数。
      - LOGIN_RATELIMIT_SECONDS=60                  # 这是来自同一 IP 的登录请求之间的平均秒数，在 Vaultwarden 限制登录次数之前。
      - ADMIN_RATELIMIT_MAX_BURST=10                # 这与 LOGIN_RATELIMIT_MAX_BURST 相同，只争对 admin 面板。
      - ADMIN_RATELIMIT_SECONDS=60                  # 这与 LOGIN_RATELIMIT_SECONDS 相同
      - ADMIN_SESSION_LIFETIME=20                   # 会话持续时间
      - ADMIN_TOKEN=YourReallyStrongAdminTokenHere  # 此值是 Vaultwarden 管理员面板的令牌（一种密码）。为了安全起见，这应该是一个长的随机字符串。如果未设置此值，则管理员面板将被禁用。建议 openssl rand -base64 48 生成 ADMIN_TOKEN 确保安全
      - SENDS_ALLOWED=true                          # 此设置决定是否允许用户创建 Bitwarden 发送 - 一种凭证共享形式。
      - EMERGENCY_ACCESS_ALLOWED=true               # 此设置控制用户是否可以启用紧急访问其账户的权限。例如，这样做可以在用户去世后，配偶可以访问密码库以获取账户凭证。可能的值：true / false。
      - WEB_VAULT_ENABLED=true                      # 此设置决定了网络保险库是否可访问。一旦您配置了您的账户和客户端，停止您的容器，然后将此值切换为 false 并重启 Vaultwarden，可以用来防止未授权访问。可能的值：true/false。
      - SIGNUPS_ALLOWED=true                        # 此设置控制新用户是否可以在没有邀请的情况下注册账户。可能的值：true / false。
      - TZ=Asia/Shanghai
